//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matchmaker
    {
        public int MatchmakingId { get; set; }
        public Nullable<int> UserIdGroom { get; set; }
        public Nullable<int> UserIdBride { get; set; }
        public Nullable<int> UserIdMatchmaker { get; set; }
        public Nullable<System.DateTime> DateWedding { get; set; }
        public string Describe { get; set; }
    
        public virtual User User { get; set; }
        public virtual Candidate Candidate { get; set; }
        public virtual Candidate Candidate1 { get; set; }
    }
}
