//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MigbalaCandidate
    {
        public int MigbalaCandidateId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> KindMigbala { get; set; }
        public Nullable<bool> Genetic { get; set; }
        public string Describe { get; set; }
        public Nullable<int> levelMigbala { get; set; }
    
        public virtual ValueList ValueList { get; set; }
        public virtual ValueList ValueList1 { get; set; }
        public virtual Candidate Candidate { get; set; }
    }
}
