//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentsOfUser
    {
        public int PaymentsOfUserId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DatePayments { get; set; }
        public Nullable<decimal> AmountToPay { get; set; }
        public string DescribePayments { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
