//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taske
    {
        public int Id { get; set; }
        public Nullable<int> kindTask { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string comment { get; set; }
        public string interestFirstName { get; set; }
        public string interestLastName { get; set; }
        public Nullable<bool> finishComment { get; set; }
        public string Tz { get; set; }
    }
}
