//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValueList()
        {
            this.MigbalaCandidates = new HashSet<MigbalaCandidate>();
            this.MigbalaCandidates1 = new HashSet<MigbalaCandidate>();
            this.ValueListCandidates = new HashSet<ValueListCandidate>();
        }
    
        public int ValueListId { get; set; }
        public Nullable<int> CriterionId { get; set; }
        public string Value { get; set; }
        public Nullable<int> Index1 { get; set; }
    
        public virtual Criterion Criterion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MigbalaCandidate> MigbalaCandidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MigbalaCandidate> MigbalaCandidates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValueListCandidate> ValueListCandidates { get; set; }
    }
}
