//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Children = new HashSet<Child>();
            this.Documents = new HashSet<Document>();
            this.Hospitalizations = new HashSet<Hospitalization>();
            this.Matchmakers = new HashSet<Matchmaker>();
            this.Matchmakers1 = new HashSet<Matchmaker>();
            this.Mechutanims = new HashSet<Mechutanim>();
            this.MigbalaCandidates = new HashSet<MigbalaCandidate>();
            this.PaymentsOfUsers = new HashSet<PaymentsOfUser>();
            this.Parents = new HashSet<Parent>();
        }
    
        public int UserId { get; set; }
        public string NamePrevMarriage { get; set; }
        public string NameRav { get; set; }
        public string TelRav { get; set; }
        public Nullable<int> EnterIn { get; set; }
        public Nullable<bool> BaitCham { get; set; }
        public string ImageCandidate { get; set; }
        public string DescribeMigbala { get; set; }
        public string personaldecription { get; set; }
        public string school { get; set; }
        public string ConfidentialityWaiverForm { get; set; }
        public Nullable<bool> payPal { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Child> Children { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospitalization> Hospitalizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matchmaker> Matchmakers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matchmaker> Matchmakers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mechutanim> Mechutanims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MigbalaCandidate> MigbalaCandidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentsOfUser> PaymentsOfUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parent> Parents { get; set; }
    }
}
