//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int MeetingId { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public string title { get; set; }
        public string Place { get; set; }
        public string tzGroom { get; set; }
        public string tzBride { get; set; }
        public Nullable<int> StatusGroom { get; set; }
        public Nullable<int> StatusBride { get; set; }
        public Nullable<int> KindMeeting { get; set; }
        public string backgroundColor { get; set; }
        public string borderColor { get; set; }
        public string textColor { get; set; }
        public string description { get; set; }
    }
}
