//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueListCandidate
    {
        public int ValueListCandidateId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CriteriaId { get; set; }
        public Nullable<int> selfValue { get; set; }
        public Nullable<int> satisfacMinValue { get; set; }
        public Nullable<int> satisfacMaxValue { get; set; }
        public Nullable<int> ValueListId { get; set; }
        public Nullable<bool> isSelf { get; set; }
        public Nullable<bool> isInclude { get; set; }
        public Nullable<bool> selfBool { get; set; }
        public Nullable<bool> satisfacBool { get; set; }
    
        public virtual Criterion Criterion { get; set; }
        public virtual User User { get; set; }
        public virtual ValueList ValueList { get; set; }
    }
}
